export const CLEAR_SPRINT = 'CLEAR_SPRINT'
export const FETCH_SPRINT_SUCCESS = 'FETCH_SPRINT_SUCCESS'
export const FETCH_SPRINT_FAILED = 'FETCH_SPRINT_FAILED'
export const CREATE_SPRINT = 'CREATE_SPRINT'
